---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

Coming into this course, my knowledge in data science was very limited. However, after taking this course, I feel confident in my ability to identify and determine various ways to analyze and utilize computational tools to create meaningful visualizations or conclusions. Of the many things that we have covered in this class, one thing I appreciate R for over other statistical languages I have learned this quarter is the ease of data cleaning. Using packages such as dplyr and tidyr that were made with the intent of efficient, readable data wrangling. Even with other more specialized packages like lubridate, I feel I have a strong understanding in the fundamental functions of these packages and can confidently apply various functions into a dplyr pipeline which streamlines the data cleaning process by having the table output of the previous function be the input into the next function. This removes the need for unnecessary objects being stored and increases the clarity of the code which is why I personally prefer data cleaning in R over other computing languages. Building the intuition on how to achieve the desired output as well as how to apply that output into other functions for statistical analysis or how to structure a visualization whether that is a table or graph that clearly communicates the information is a skill I believe I have developed over the quarter. One thing that I believe I have developed is an eye for detail in the aesthetics of these graphs,

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

I believe that my code from challenge 7 demonstrates my understanding on various modifications and details I can apply to graphs using ggplot and other packages by using a dplyr pipeline directly into the ggplot removing the need to store the table as an object. Other aspects of this code is the use of reordering the legend by the fish type factor, which makes it easier for the audience to see which line goes to which. By faceting by trip, there is a side-by-side comparison between the two trips, which can be visually observed and see the common trends across both as well as the differences, though some might argue that if we wanted to observed how the two compared over time by species, it would have been better to graph the two trips on one graph and facet by species. Of course, there are ways I could improve this graph as well such as adding an annotation at the peak, or creating a rectangle and highlighting a specific time period, however I did not find enough context to highlight a specific time frame, but it would've been nice. Such annotations can be convenient in the case that I wanted to predict future condition indexes, distinguishing when that time would be. However I think that goes beyond the content in this course and what we have learned. I think that being able to think of ways to improve the graph and future directions for this plot as well demonstrates how I have grown as a data scientist and have a good idea on the next steps I could take to further improve my skills that go beyond what we have learned in this course.
